Part A: Basic NumPy Array Operations

In [2]:
import numpy as np

# Task 1a: 1D array 1 to 20
arr1 = np.arange(1, 21)
print("1D Array:", arr1)

# Task 1b: 5x5 zero matrix
zero_mat = np.zeros((5, 5))
print("\n5x5 Zero Matrix:\n", zero_mat)

# Task 1c: 4x4 identity matrix
identity_mat = np.eye(4)
print("\n4x4 Identity Matrix:\n", identity_mat)

# Task 1d: evenly spaced values between 10 and 50
even_array = np.arange(10, 51, 5)
print("\nEvenly Spaced Array (10 to 50):\n", even_array)

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

5x5 Zero Matrix:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Evenly Spaced Array (10 to 50):
 [10 15 20 25 30 35 40 45 50]


Task 2: Array Attributes

In [3]:
# Create a sample array
arr = np.arange(1, 13).reshape(3, 4)

print("Array:\n", arr)

# Shape (rows, columns)
print("\nShape:", arr.shape)

# Dimensions (1D, 2D, etc.)
print("Dimensions:", arr.ndim)

# Data type
print("Data Type:", arr.dtype)

# Total number of elements
print("Size:", arr.size)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Dimensions: 2
Data Type: int64
Size: 12


Part B: Indexing and Slicing

In [4]:
import numpy as np

# Given array
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120],
                [130, 140, 150, 160]])

print("Original Array:\n", arr)

# a) First row
first_row = arr[0]
print("\nFirst Row:\n", first_row)

# b) Last column
last_col = arr[:, -1]
print("\nLast Column:\n", last_col)

# c) Subarray (example: first 2 rows and first 3 columns)
subarray = arr[:2, :3]
print("\nSubarray (2x3):\n", subarray)

# 4) Modify array values using indexing
arr[1, 2] = 999   # change one value
print("\nModified Array:\n", arr)

Original Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

First Row:
 [10 20 30 40]

Last Column:
 [ 40  80 120 160]

Subarray (2x3):
 [[10 20 30]
 [50 60 70]]

Modified Array:
 [[ 10  20  30  40]
 [ 50  60 999  80]
 [ 90 100 110 120]
 [130 140 150 160]]


Part C: Mathematical Operations

In [5]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

# Addition
print("Addition:", a + b)

# Subtraction
print("Subtraction:", a - b)

# Multiplication
print("Multiplication:", a * b)

# Division
print("Division:", a / b)

# Dot Product
print("Dot Product:", np.dot(a, b))

Addition: [ 3  7 11]
Subtraction: [1 1 1]
Multiplication: [ 2 12 30]
Division: [2.         1.33333333 1.2       ]
Dot Product: 44


5. Calculate mean, median, standard deviation, maximum, and minimum values.

In [6]:
data = np.array([12, 25, 37, 45, 58, 63, 71])

print("\nData:", data)

# Mean
mean_val = np.mean(data)
print("Mean:", mean_val)

# Median
median_val = np.median(data)
print("Median:", median_val)

# Standard Deviation
std_val = np.std(data)
print("Standard Deviation:", std_val)

# Maximum value
max_val = np.max(data)
print("Maximum:", max_val)

# Minimum value
min_val = np.min(data)
print("Minimum:", min_val)


Data: [12 25 37 45 58 63 71]
Mean: 44.42857142857143
Median: 45.0
Standard Deviation: 19.71117987957337
Maximum: 71
Minimum: 12


Part D: Multidimensional Arrays

6. Perform matrix operations including addition, multiplication, transpose, and
determinant.

In [7]:
import numpy as np

# Define two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

# ➤ Matrix Addition
add = A + B
print("\nAddition:\n", add)

# ➤ Matrix Multiplication (element-wise)
element_mul = A * B
print("\nElement-wise Multiplication:\n", element_mul)

# ➤ Matrix Multiplication (dot product)
dot_mul = np.dot(A, B)
print("\nDot Product (Matrix Multiplication):\n", dot_mul)

# ➤ Transpose
transpose_A = A.T
print("\nTranspose of A:\n", transpose_A)

# ➤ Determinant
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Dot Product (Matrix Multiplication):
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Determinant of A: -2.0000000000000004


7. Reshape arrays into different dimensions and explain reshaping.

In [8]:
import numpy as np

# 1D array
arr = np.arange(1, 13)

print("Original Array (1D):\n", arr)

# ➤ Reshape to 3x4
arr_3x4 = arr.reshape(3, 4)
print("\nReshaped (3x4):\n", arr_3x4)

# ➤ Reshape to 4x3
arr_4x3 = arr.reshape(4, 3)
print("\nReshaped (4x3):\n", arr_4x3)

Original Array (1D):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Part E: Real-Life Mini Problem

8. Analyze student marks using NumPy arrays.

In [9]:
import numpy as np

# Each row = one student
# Columns = 3 subjects (e.g., Math, Physics, English)
marks = np.array([
    [85, 90, 78],
    [70, 88, 92],
    [60, 75, 80],
    [95, 89, 94],
    [55, 65, 70]
])

print("Student Marks:\n", marks)

Student Marks:
 [[85 90 78]
 [70 88 92]
 [60 75 80]
 [95 89 94]
 [55 65 70]]


9. Calculate averages, identify highest marks, and filter students based on conditions.

In [10]:
avg_marks = np.mean(marks, axis=1)
print("\nAverage Marks of Each Student:\n", avg_marks)


Average Marks of Each Student:
 [84.33333333 83.33333333 71.66666667 92.66666667 63.33333333]


In [11]:
highest = np.max(marks)
print("\nHighest Mark in Dataset:", highest)


Highest Mark in Dataset: 95


In [12]:
lowest = np.min(marks)
print("Lowest Mark in Dataset:", lowest)

Lowest Mark in Dataset: 55


In [13]:
top_students = avg_marks > 80
print("\nStudents with Average > 80:", top_students)
print("Filtered Average Marks:", avg_marks[top_students])


Students with Average > 80: [ True  True False  True False]
Filtered Average Marks: [84.33333333 83.33333333 92.66666667]


In [14]:
passed_students = np.all(marks > 40, axis=1)
print("\nStudents who passed all subjects:", passed_students)


Students who passed all subjects: [ True  True  True  True  True]


In [15]:
best_student_index = np.argmax(avg_marks)
print("\nBest Student Index:", best_student_index)
print("Best Student Marks:", marks[best_student_index])


Best Student Index: 3
Best Student Marks: [95 89 94]
