<a href="https://colab.research.google.com/github/MstMahfuzaAkter/AL_LAB/blob/main/OOP%2CNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Class and Objects

In [ ]:
# class attribute
class Phone:
    category = "Electronics"

    # constructor
    def __init__(self, model, battery, camera, battery_percentage=100):
        self.model = model
        self.battery = battery
        self.camera = camera
        self.battery_percentage = battery_percentage

    # method
    def charge(self, hour):
        print(f"Charge is complete: {hour} hour(s)")

    def capture(self, total_photo):
        if self.battery_percentage <= 0:
            print("No charge")
        else:
            self.battery_percentage -= total_photo
            print(f"Photo Capture in {self.model}")


class Cooling_Mechanism:
    def __init__(self, cooling_method):
        self.cooling_method = cooling_method

    def cooling_on(self):
        print(f"The system is being cooled by {self.cooling_method}")

In [ ]:
#creating object

#apple=Phone()
apple.category="Super Electronics"
#print(type(apple))
#blueberry=Phone()
#motorola=Phone()


print(apple.category)
#print(blueberry.category)
#print(motorola.category)

apple=Phone("Iphone17",3000,40)
blueberry=Phone("B-17",4000,30)
motorola=Phone("M-17",3500,35)

print(apple.camera)

print(motorola.battery_percentage)

motorola.capture(10)
print(motorola.battery_percentage)



Super Electronics
40
100
Photo Capture in M-17
90


OOP Inheritance

In [ ]:
class Smartphone(Phone):
    def __init__(self, model, battery, camera, processor):
        super().__init__(model, battery, camera)
        self.processor = processor

    def charge(self, hour):
        print("Fast charging in process")
        super().charge(hour)

In [ ]:
pro=Smartphone("X",5000,100,"SnapDragon")

print(pro.model)
pro.charge(1)



X
Fast charging in process
Charge is complete :1


Multiple Inheritance

In [ ]:
class SmartPhn_Cooling(Smartphone,Cooling_Mechanism):
  def __init__(self, model, battery, camera, processor,cooling_method):
     Smartphone.__init__(self,model, battery, camera, processor)
     Cooling_Mechanism.__init__(self,cooling_method)


In [ ]:
pro_cooling=SmartPhn_Cooling("Y",5000,30,"SnapDragon","Nitrogen")
print(pro_cooling.processor)

print(pro_cooling.cooling_on())
pro_cooling.charge(1)

SnapDragon
The system is being cooled by Nitrogen
None
Fast charging in process
Charge is complete :1


OOP Polymorphism-->overriding

In [ ]:
class Camera:
  def __init__(self,name):
      self.name=name
  def capture(self):
    print("a photo is capture")


In [ ]:
class Smart_Phone(Camera):
  def __init__(self, name,resolution):
      super().__init__(name)
      self.resolution=resolution

  #method override
  def capture(self):
     print("Photo is capture by a phone")
class DSLR(Camera):
  def __init__(self,name,resolution):
    super().__init__(name)
    self.resolution=resolution

  def capture(self):
     print("Photo is capture by a dslr")

class Drone(Camera):
  def __init__(self,name,resolution):
    super().__init__(name)
    self.resolution=resolution

  def capture(self):
     print("Photo is capture by a drone")



In [ ]:
phone=Smart_Phone("Phpne",60)
dslr=DSLR("DSLR",200)
drone=Drone("Drone",400)

phone.capture()
dslr.capture()
drone.capture()

Photo is capture by a phone
Photo is capture by a dslr
Photo is capture by a drone


Encapsulation-->data+method ke encap,protected korbo

In [ ]:
class Mobile:
  def __init__(self,name,model,imei):
    self.name=name
    self.model=model
    self.imei=imei
  def charger(self):
    print("Phone is charging")

IPhone =Mobile("Phone","17","!xkaf1")
print(IPhone.imei)
print(IPhone.name)
IPhone.name="Ph"
print(IPhone.name)
IPhone.charger()

!xkaf1
Phone
Ph
Phone is charging


In [ ]:
class Mobile1:
  def __init__(self,name,model,imei):
    self.__name=name #private
    self.__model=model#private
    self.__imei=imei ##private
  def charger(self):
    print("Phone is charging")


#imei pete pari
  def imei_getter(self):
    return self.__imei
  #model ta ke dekhte pari

  def model_getter(self):
    return self.__model

  def name_getter(self):
    return self.__name

  def name_setter(self,name):
    self.__name=name

#outside


IPhone =Mobile1("Phone","17","!xkaf1")
print(IPhone.imei_getter())
print(IPhone.name_getter())
print(IPhone.model_getter())
IPhone.name_setter("OKKKK")
print(IPhone.name_getter())
IPhone.charger()

!xkaf1
Phone
17
OKKKK
Phone is charging


 Abstraction--->complex method ke hide kore operate korer jonno funtion/method provide korbo

In [ ]:
from abc import ABC, abstractmethod

class Telephone(ABC):
    @abstractmethod
    def make_call(self):
        pass

    @abstractmethod
    def capture_photo(self):
        pass


class Sphone(Telephone):
    def make_call(self):
        print("Making a call from Sphone")

    def capture_photo(self):
        print("Sphone capturing photo")


class Iphone(Telephone):
    def make_call(self):
        print("Making a call from Iphone")

    def capture_photo(self):
        print("Iphone capturing photo")

In [ ]:
ip=Iphone()
ip.make_call()

Making a call from Iphone


NumPy-->numerical python,fast mathematical dey
Advantages:
Ndarray-->N dimensional array
list slow but Ndarray fast,,
continous,,
homogenes,,
vectorization-->single instruction multiple data(SIMD) CPU te thake,,
linear algebra,math,statistic niye kaj kore



In [ ]:
arr=[1,2,3]
print(arr*5)

arr=[x*5 for x in arr]
print(f"array{arr}")

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
array[5, 10, 15]


In [ ]:
import numpy as np
arr1=np.array([1,2,3])

arr1=arr1*5
print(type(arr1))
print(arr1.ndim)
print(arr1)

arr2=np.array([[1,2,3],
               [4,5,6]
              ])
print(arr2)
print(arr2.ndim)

#3d array

arr3=np.array([[
    #1st floor
    [1,2,3],
     [4,5,6]
    ],
     [
         #2nd floor
         [7,8,9],
          [1,2,3]
      ]
               ])
print(arr3.ndim)


<class 'numpy.ndarray'>
1
[ 5 10 15]
[[1 2 3]
 [4 5 6]]
2
3


In [ ]:
#array attribute
#dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#data type

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(3,)
(2, 3)
(2, 2, 3)
int64
int64
int64
3
6
12


Ndarray Data Type


In [ ]:
arr=np.array([1,2,3.5])
print(arr.dtype)


#upcasted to string
arr=np.array([1,2,3.5,'a'])
print(arr.dtype)

#selectimg a data type  for any array

arr=np.array([1,2,3],dtype=np.int8)#[-127 to 128]
print(arr.dtype)
arr=arr.astype(np.int16)
print(arr.dtype)


float64
<U32
int8
int16
